# Efficiency in Theory: Time & Memory Complexity

## 1) Time Complexity

When analysing algorithms we focus on **how runtime grows** with input size **n**.

Common complexities (by Big-O notation):

| Complexity | Complexity Name | Algorithmic Example |
|------------|-----------------|---------------------|
| O(1)       | constant        | dictionary lookup   |
| O(log n)   | logarithmic     | heap insertion      |
| O(n)       | linear          | scanning a list     |
| O(n log n) | linearithmic    | sorting             |
| O(n²)      | quadratic       | double nested loops |

Important:
- In Python, dictionary operations are O(1) on average because of hashing.
- Worst case can degrade, but it is rare in practice.

**Information nugget:**
Alongside Big-O, there are also Big-Omega (Ω) and Big-Theta (Θ) notations.

- Ω: asymptotic lower bound (algorithm grows at least this fast)
- O: asymptotic upper bound (algorithm grows at most this fast)
- Θ: asymptotically tight bound (both upper and lower bound)

In many courses, Big-O is emphasized because it is often used to describe worst-case running time.

### 1.1) Seconds in Runtime vs. Time Complexity

Runtime (seconds) and time complexity are related but different.

- **Runtime**: actual execution time on a specific machine.
- **Time complexity**: how runtime scales with input size $n$ (e.g., $O(n)$, $O(n^2)$), independent of hardware.

So two computers can run the same algorithm at different speeds, but the complexity class stays the same.

## 2) Memory Complexity

Memory complexity measures **how much extra space** an algorithm needs.

| Data Structure | Memory Behaviour               |
|----------------|--------------------------------|
| list           | contiguous array               |
| dictionary     | hash table with extra overhead |
| heap           | stored as a list               |

Dictionaries usually require more memory than lists because they store keys, values, and hashing metadata.

## 3) Examples

#### Sum of the numbers in an array

In [1]:
import random as rd

# Create a random array of 10 integers between 1 and 100
array = rd.sample(range(1, 100), 10)
print("Array:", array)

# Calculate the sum of the array
sum = 0
for i in array:
    sum += i
print("Sum:", sum)

Array: [78, 11, 26, 47, 40, 20, 31, 70, 55, 6]
Sum: 384


#### Matrix multiplication

In [2]:
import numpy as np

# Create two random matrices
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Matrix multiplication for naive approach
C = np.zeros((3, 3), dtype=int)
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

print("\nResult C = A x B:")
print(C)

# Verify with numpy
print("\nVerification with numpy:")
print(np.matmul(A, B))

Matrix A:
[[3 2 8]
 [2 1 5]
 [8 8 3]]

Matrix B:
[[3 4 3]
 [6 6 4]
 [4 8 4]]

Result C = A x B:
[[ 53  88  49]
 [ 32  54  30]
 [ 84 104  68]]

Verification with numpy:
[[ 53  88  49]
 [ 32  54  30]
 [ 84 104  68]]


#### **Question**: What are the time and memory complexities of the above examples?

#### **Answer**

| _Complexity_      | Array - Sum | Matrix - Multiplication |
|-------------------|-------------|-------------------------|
| Time Complexity   | $O(n)$      | $O(n^3)$                |
| Memory Complexity | $O(n)$      | $O(n^2)$                |

Note: Memory complexity of "Matrix - Multiplication" is caused by $C[i][j]$. It is the cost of keeping a matrix which is indeed a 2D array.

## 4) Helpful Links

Time complexity [cheat sheet](https://www.bigocheatsheet.com).

Time complexity analysis specifically for [Python data structures](https://wiki.python.org/moin/TimeComplexity).

⭐ [Visualisations](https://visualgo.net/en) of data structures and algorithms.

AI-based free time complexity analysis + reasoning:
- https://www.bigocalc.com *(also provides space complexity)*
- https://www.timecomplexity.ai